name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inorbit
    volumes:
      - pg_data:/bitnami/postgresql

volumes:
  pg_data:
    driver: local
